### ISSUE TITLE
[Bug]: Dark Oak Growth

### ISSUE THREAD

**Issue by SpectrumSmoke** [dr3ams/Industrial-Village#11]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

GDL

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

Dark Oak trees, while still requiring 2x2 saplings, grow on a single block. Only really an issue with MineColonies, where foresters will only replant the one sapling and thus the trees won't regrow. Also leaves graphical errors of the saplings where the the other three, non-grown saplings are that can only be removed by right-clicking them or placing another item in its space.

### Steps to reproduce the issue

1. Plant a 2x2 area of dark oak saplings. 2. Grow the tree. 3. Attempt to break the remaining three saplings.

### Additional Information

![Screenshot (112)](https://github.com/dr3ams/Industrial-Village/assets/172636967/e82084bb-c660-4c5e-b447-1471892bd3d3)

**Comment by Gunner76th** [comment]
This is a known issue caused by the tree mod that is in the modpck. It affects all trees that have a planting pattern of more than 1x1

**Comment by dr3ams** [comment]
Will be changed in the next update
