### ISSUE TITLE
[Bug]: Game crash when i try to open/create world

### ISSUE THREAD

**Issue by miisha557** [dr3ams/Industrial-Village#12]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism launcher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

A bug happened!

### Steps to reproduce the issue

[crash-2024-06-14_16.59.36-server.txt](https://github.com/user-attachments/files/15835790/crash-2024-06-14_16.59.36-server.txt)

### Additional Information

[latest.log](https://github.com/user-attachments/files/15835858/latest.log)

**Comment by ScriptAero** [comment]
https://github.com/dr3ams/Industrial-Village/issues/8#issuecomment-2155024302
