### ISSUE TITLE
[Bug]: The recipe for the wooden form is just a wooden form plus a wooden form crafts a wooden form

### ISSUE THREAD

**Issue by fastman241** [dr3ams/Industrial-Village#15]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

The recipe for the wooden form is just a wooden form plus a wooden form crafts a wooden form
![image_2024-06-14_162111186](https://github.com/dr3ams/Industrial-Village/assets/135450728/963b09a6-715e-4042-90c2-ae2732757fbd)

### Additional Information

I dont have any additinal info

**Comment by Gunner76th** [comment]
Click on the Cutting Board tab. Not everything is made in the Crafting Table

Not a bug, PEBKAC

**Comment by dr3ams** [comment]
![image](https://github.com/dr3ams/Industrial-Village/assets/7347489/9ef70cf3-70d2-43ec-a025-d6ce699b7934)
