### ISSUE TITLE
[Bug]: item unloaded/loader recipe

### ISSUE THREAD

**Issue by ZinxSlayerz** [dr3ams/Industrial-Village#17]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5 

### Describe your issue

the recipe for the advanced item loader and unloader requires a steel shovel. the steel shovel it requires is uncraftable and does not show up in JEI. I have tried to craft the recipe with the other steel shovel in the pack that shows in JEI but it doesn't work

### Steps to reproduce the issue

check the recipe for the advanced item loader/unloader

### Additional Information

![image](https://github.com/dr3ams/Industrial-Village/assets/107813462/16b71704-772d-4183-a672-79656615e954)
![image](https://github.com/dr3ams/Industrial-Village/assets/107813462/043f0aa1-1f94-4b9b-8060-baba525e22eb)

**Comment by dr3ams** [comment]
fixed in 1.6c
