### ISSUE TITLE
Making compressed iron in the arc furnace isn't working only makes steel [Bug]: 

### ISSUE THREAD

**Issue by duckielord12** [dr3ams/Industrial-Village#18]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

Im following what JEI says to do add 2 tnt and 1 iron to the arc furnace but it doesnt make the compressed iron only makes steel and idk what to do 

### Steps to reproduce the issue

1. put in the exact ingredients 2. wait 3. outputs steel instead 

### Additional Information

its not crashing just very confusing

**Comment by Stoettho** [comment]
Sorry to bother a closed issue but what was the solution?

**Comment by Gunner76th** [comment]
> Sorry to bother a closed issue but what was the solution?

You put TNT in the left side, Iron in the right side. There is no way this would have made steel using TNT and Iron.
