### ISSUE TITLE
[Bug]: Crashing when trying to create a singleplayer world

### ISSUE THREAD

**Issue by sssillyyyy** [dr3ams/Industrial-Village#19]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

PrismLauncher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

Keeps crashing when I load/generate a singleplayer world, haven't been able to play the pack

### Steps to reproduce the issue

1. Start pack 2. Create Singleplayer world

### Additional Information

[crash-2024-06-22_17.24.30-server.txt](https://github.com/user-attachments/files/15936196/crash-2024-06-22_17.24.30-server.txt)

**Comment by ScriptAero** [comment]
https://github.com/dr3ams/Industrial-Village/issues/8#issuecomment-2155024302
