### ISSUE TITLE
[Bug]: Water wheel both invisble and not generating power.

### ISSUE THREAD

**Issue by PouncingChicken** [dr3ams/Industrial-Village#21]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

I've been grinding through the early game and was attempting to build a immersive engineering water wheel when I realized 1. I couldn't see the wheel and 2. The wheel was not generating any power. I have a proper setup and everything as I have already researched a guide on the proper setup. I also looked for a few fixes for the invisible texture. I already turned off my VBO in the client settings for Immersive engineering to no avail. 

Any ideas? I really like the pack and hope I can continue playing it.

### Steps to reproduce the issue

![2024-06-25_21 35 57](https://github.com/dr3ams/Industrial-Village/assets/173872640/a3632280-99db-444e-b141-5451d287e6c7)

### Additional Information

[2024-06-25-2.log.gz](https://github.com/user-attachments/files/15982490/2024-06-25-2.log.gz)
This log is the most recent crash, however I am not crashing often, I simply am adding this log to not immediately have my bug report deleted due to the notice at the bottom of the crash report screen.

**Comment by Gunner76th** [comment]
You have nothing connecter to the dynamo right now.  Dynamos do not have any internal storage so it won't show any power.  You need to connect it to an accumulator or something that requires power.

**Comment by PouncingChicken** [comment]
There are three water wheels connected to the dynamo, they are simply invisible. I understand it doesn't have a bank for power to move into, but before I can even start on doing that part I need to be able to see the wheels and check if they are turning.

> You have nothing connecter to the dynamo right now. Dynamos do not have any internal storage so it won't show any power. You need to connect it to an accumulator or something that requires power.

**Comment by Gunner76th** [comment]
The issue with not being able to see the wheels is because you're using shaders.  Disable your shaders and they should show up.  Also you don't need to see them to know they're spinning,  the fact your water isn't falling means they are spinning.
