### ISSUE TITLE
[Suggestion]: Allow configuration for personal usage

### ISSUE THREAD

**Issue by Rochjiboy** [dr3ams/Industrial-Village#22]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Hey, how do I revert some of the mod's original configuration? I have already finished the mod pack and have started to add more worlds and such and I wanted to return the Sophisticated Backpack to its original settings i.e. getting back all the other upgrades. It is also one of my buddies' complaints because they used and liked some of the upgrades as well.

**Comment by ScriptAero** [comment]
Sorry but no. We will not support people with modified game files.
