### ISSUE TITLE
[Bug]: Bad recipe for Graphite Electrode

### ISSUE THREAD

**Issue by mokinys98** [dr3ams/Industrial-Village#27]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Forge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6b

### Describe your issue

1.5 version showed correct recipe that 4 HOP ingots to 1 electrode
After updating, I guess "Just Enough Immersive Multiblocks" preview is not configured for this recipe
[image](https://github.com/dr3ams/Industrial-Village/assets/45077974/51443acc-ccd3-442b-88aa-f08a1fdbf432)

### Additional Information

It dosent crash so need to upload anything 
[latest.log](https://github.com/user-attachments/files/16116615/latest.log)
[latest.log](https://github.com/user-attachments/files/16116619/latest.log)

**Comment by Barinzaya** [comment]
*Many* of the IE recipes seem to be broken as of 1.6b (not sure if this is also true in 1.6a, I went straight from 1.5 to 1.6b). They all seem to show quantities of 1 for everything, even when that's not the case.

Other examples:
* Making metal rods in the metal press shows 1 ingot to 1 rod; it should be 2 rods.
* Making iron/steel mechanical components in the workbench shows 1 plate + 1 copper ingot to 1 component; it should be 2 plates.

**Comment by Barinzaya** [comment]
After a quick test, this issue *does* still seem to occur with Just Enough Immersive Multiblocks disabled, so it's not specifically that mod.

**Comment by Barinzaya** [comment]
This seems to affect more than just IE. I'm now getting into PneumaticCraft, and I'm finding that Turbine Blades show that they require 1 gold and 2 redstone, but they actually seem to require 2 redstone.

**Comment by dr3ams** [comment]
There seems to be a problem with EMI
https://www.curseforge.com/minecraft/mc-mods/emi
You can manually update it, I'm not sure if I can get a hotfix released soon enough

**Comment by Barinzaya** [comment]
Can confirm, updating EMI specifically seems to fix the recipe issues. Thanks for the info!
