### ISSUE TITLE
[Bug]: No craft for nether bricks

### ISSUE THREAD

**Issue by AgraveFR** [dr3ams/Industrial-Village#31]
### General Info

- [X] I didn't add any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6b

### Describe your issue

It's impossible to craft nether bricks from netherrack or any other source than strip down a nether forteresse

### Steps to reproduce the issue

1. Don't craft netherbricks

### Additional Information

NA

**Comment by Gunner76th** [comment]
This is intentional.

**Comment by AgraveFR** [comment]
That's too bad, i  want to used some for decoration

**Comment by Gunner76th** [comment]
Last I knew you can take harvested nether brick and reduce them down to individual bricks
