### ISSUE TITLE
[Suggestion]: Storage Drawers

### ISSUE THREAD

**Issue by Mrivanov1** [dr3ams/Industrial-Village#33]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I want the mod Storage Drawers to be added since I go mining a lot and I get a lot of cobblestone and other stuff, I already have a million chests and also sharing my base with 2 other friends, we try to keep out chests organized so we don't lose stuff but it's hard with so many items. Thank you for your time!

**Comment by Gunner76th** [comment]
Modpack already contains Functional Storage which is the same thing as Storage Drawers.
