### ISSUE TITLE
[Suggestion]: Just Enough Resources

### ISSUE THREAD

**Issue by Mrivanov1** [dr3ams/Industrial-Village#34]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

This mod would be good if you are searching for a specific item but you don't know how to get it, but it's a mod drop, but you don't know that! You search the internet to find it and it takes much longer than it should!

**Comment by dr3ams** [comment]
we have https://www.curseforge.com/minecraft/mc-mods/emi-loot for that
