### ISSUE TITLE
[Bug]: Any immersive engineering gadgets do not produce energy

### ISSUE THREAD

**Issue by GaLenN3228** [dr3ams/Industrial-Village#38]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Legacy Launcher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6c

### Describe your issue

Building any rf generators, and get 0 energy 

### Steps to reproduce the issue

just build something lake water wheel e.t.c

### Additional Information

i can provide any information on discrord and cast my screen

**Comment by Gunner76th** [comment]
We do not provide support for illegal or cracked launcher use. If you legally own minecraft you will be required to use one of the following launchers and reproduce the issue:

Curseforge
ATLauncher
GDLauncher
PrismMC
FTB Launcher
