### ISSUE TITLE
[Bug]:_crashing_when_killed_by_a_ranger_skeleton

### ISSUE THREAD

**Issue by Sosborso** [dr3ams/Industrial-Village#4]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.0

### Describe your issue

A bug happened! this problem accured twice since i started playing(not long). and when i go to the point of my death there is no corpse nor items just the xp.

### Steps to reproduce the issue

1.find a ranger skeleton 2.get killed by the skeleton

### Additional Information

[latest.log](https://github.com/dr3ams/Industrial-Village/files/14806511/latest.log)
[crash-2024-03-29_14.52.44-server.txt](https://github.com/dr3ams/Industrial-Village/files/14806517/crash-2024-03-29_14.52.44-server.txt)
[crash-2024-03-29_17.22.52-server.txt](https://github.com/dr3ams/Industrial-Village/files/14806521/crash-2024-03-29_17.22.52-server.txt)

**Comment by dr3ams** [comment]
Fixed by disabling v-tweaks wandering trader feature
