### ISSUE TITLE
[Bug]: Crash after joining the world

### ISSUE THREAD

**Issue by StivetShoy** [dr3ams/Industrial-Village#45]
### General Info

- [ ] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.7b

### Describe your issue

My save has started to crash sometimes, but now it crashes everytime when i join my world. Logs say it is something with farmer's AI. Maybe it is because I gave him farmers delight seeds, but Im not sure. If I try to downgrade my modpack version to 1.6c or try to delete Minecolonies Tweaks and Compatibillity, the colony just disappears (citizens disappears, blocks say that theyre missing its building, /mc colony list have 0 colonies). Help, I dont know what to do.

### Additional Information

[latest.log](https://github.com/user-attachments/files/16619562/latest.log)

**Comment by Gunner76th** [comment]
If you would, please also get the actual crash report which is found in the /crash-reports/ folder.

**Comment by StivetShoy** [comment]
[crash-2024-08-15_01.22.27-server.txt](https://github.com/user-attachments/files/16623686/crash-2024-08-15_01.22.27-server.txt)

**Comment by StivetShoy** [comment]
New version of minecolonies tweaks and compatability fixed it
