### ISSUE TITLE
[Bug]: Screen cutting issue

### ISSUE THREAD

**Issue by Collierson** [dr3ams/Industrial-Village#49]
### General Info

- [ ] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6b

### Describe your issue

At a certain moment during gameplay, I noticed that the entire game screen had shifted to the right. I had to move the mouse slightly to the left of an item slot to be able to click on the item. The right side of the game screen, as well as the right side of the inventory, was cut off. This issue only occurs within this modpack, and I did not notice this phenomenon when playing the vanilla game.

### Steps to reproduce the issue

1.Screen cutting
1.Screen and mouse click do not align

### Additional Information

![image](https://github.com/user-attachments/assets/65f8941d-93d7-4b01-ae74-94327d20fe37)
![image](https://github.com/user-attachments/assets/8fa86258-ba1f-4ebc-bdbd-cee4b72de372)
![image](https://github.com/user-attachments/assets/607464f8-326a-4389-9385-c53e9fb4f9bd)

**Comment by Gunner76th** [comment]
This is a known issue when you're wearing an elytra in the chest armor slot.  Instead wear the elytra in the curios back slot and this issue won't happen.

**Comment by gamma-delta** [comment]
I'm also having this issue -- I've poked through the modlist and I can't figure out what mod is causing it. My guess is *why* it's happening is that whichever mod is rendering the little elytra icon alongside the armor bar on the in-game HUD forgot to reset the `PoseStack` properly. So everything is offset by the width of that icon.

That icon doesn't appear to be from either Caelus or Elytra Slot (I checked their Githubs).

Irritatingly this also happens with the Immersive Engineering Collapsible Glider, which *doesn't* go into the special elytra slot. As a bandaid fix you might want to allow the glider into there until someone figures out the source of the real problem.

**Comment by gamma-delta** [comment]
It's also not:
- Inventory HUD+. Thank god, cause that mod's closed-source.
- Armourer's Workshop
- Overflowing Bars
- Zeta

I only actually ran the game with the first one, the other three were me just checking their githubs for the texture.

**Comment by gamma-delta** [comment]
Aha, the rendered elytra icon is from Quark.

I think it's definitely because they're shifting the whole UI to the right to make the armor bar render to the right, [see here](https://github.com/VazkiiMods/Quark/blob/master/src/main/java/org/violetmoon/quark/content/client/module/ElytraIndicatorModule.java#L48). Genuinely I'm not sure why it works in vanilla, but my guess is that there's some other mod hooking into just the wrong moment... will go continue debugging on their issue tracker.

**Comment by gamma-delta** [comment]
As a hotfix you can disable Overflowing Bars.
