### ISSUE TITLE
[Bug]: Tunnel Bore [RAILCRAFT] Block Placer [IFG]

### ISSUE THREAD

**Issue by hikinata** [dr3ams/Industrial-Village#51]
### General Info

- [X] I didn't add any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

IV-1.20.1.7b

### Describe your issue

Hello, I have two concerns that I think may be related.

The first is for the bore tunnel, from railcraft, in fact the machine does not break any blocks..
Whether in a claimed location or not, and outside colonies.

And the second is that the block placement of industrial foregoing, does not place any blocks.

I saw solutions that said to change the FTB teams settings, but I don't have these settings.

Do you have a solution?

### Steps to reproduce the issue

1. Use tunnel bore of railcraft in multiplayer world.
2. Use block placer of industrial foregoing in multiplayer world

### Additional Information

no crash

**Comment by Gunner76th** [comment]
This is due to either Open Parties and Claims settings for your claim/wilderness or due to protections that are applied by Minecolonies if you are doing this within a colony. You need to adjust the settings to allow fake players to do work in your claim in OPAC or add the fake player to the permissions in your colony.  This will fix your issue. This is not a bug, but the protection systems working as intended.

**Comment by Gunner76th** [comment]
These arent things you do in the config. You would do these in game using either the OPAC GUI to set the permissions, or in the Town Hall to add permissions for the Fake Player

**Comment by hikinata** [comment]
it's ok with OPAC, i haven't see this menu ! Sorry and thank you
