### ISSUE TITLE
[Bug]: game crashes when creating a world

### ISSUE THREAD

**Issue by moos4** [dr3ams/Industrial-Village#8]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

prism launcher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

when i make a new world i first get the normal world settings menu, but when i click "create new world" it just crashes

### Steps to reproduce the issue

1: click on singleplayer 2: (only needed if you already have a world) click on create new world 3: click on create new world in the world setting menu thing 4: crash

### Additional Information

[latest.log](https://github.com/user-attachments/files/15741345/latest.log)
[crash-2024-06-07_16.50.11-server.txt](https://github.com/user-attachments/files/15741348/crash-2024-06-07_16.50.11-server.txt)

**Comment by ScriptAero** [comment]
The fix for this is to replace a certain datapack, with the file I am about to provide. You will want to go to your instance -> config -> paxi -> datapacks and replace files in destination. Make sure you unzip the file I am going to provide.
[structory.zip](https://github.com/user-attachments/files/15741475/structory.zip)
