### ISSUE TITLE
[Bug]: Iron Sheetmetal Crafting + No way to farm enough Iron

### ISSUE THREAD

**Issue by JoonesBP** [dr3ams/Industrial-Village#9]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

1. The iron sheetmetal needed throughout doesn't seem craftable, all the other sheetmetal types have recipes but the iron does not (as far as I can see)

2. Iron is super necessary for steel and other stuff yet I can't find anything in the quest book about producing more iron than the little amount found underground, am I missing something?

Sorry if these don't count as bugs, I am new to github (made the account today to address these problems im having) and just really wanted assistance to keep progressing, thank you for the help.

PS: You mentioned a discord (which i imagine would be more fit for these kind of questions) but I can't find a link, where can i find this?

### Additional Information

No logs as it is the crafting recipe and the iron problem.

**Comment by ScriptAero** [comment]
You can do /discord in game to get access to it, and it is craftable you need the powered rolling machine.

**Comment by JoonesBP** [comment]
> You can do /discord in game to get access to it, and it is craftable you need the powered rolling machine. There are also PLENTY of ways to obtain iron.

The /discord command isn't working, says it's unrecognised, could you send a link please. Also what are these ways to obtain iron, i am happy to ask in the discord if you send a link

**Comment by ScriptAero** [comment]
https://discord.com/invite/dreams-modpacks-512339624627011586
